// Generates the icon font + an SCSS partial listing every glyph.
//
// Class pattern: .icon (base) + .icon--<svg-filename> (modifier).
// Example: <i class="icon icon--search" aria-hidden="true"></i>
//
// Regenerate after adding/removing SVGs:  npm run icons

module.exports = {
  name: 'icons',
  inputDir: './assets/svg',
  // Fonts go into src/public/ so Vite serves them from the site root
  // (/fonts/icons/…) — the @font-face URL in the generated SCSS can stay
  // absolute, which sidesteps Sass/Vite relative-URL resolution across
  // @forward boundaries.
  outputDir: './src/public/fonts/icons',
  fontTypes: ['woff2', 'woff'],
  // Only emit the codepoints JSON — the companion SCSS partial is generated by
  // scripts/build-icons-scss.cjs so we control font-display, url paths, and
  // modern Sass module syntax ourselves.
  assetTypes: ['json'],
  normalize: true,
};
